# This script is used to check the number of files in the output directory.
# It checks the following:
# - The number of generated images
# - The number of prompt files
# - The number of score files (including the diversity)
# Note: This script is generated by the Claude 4.5 Sonnet model.


from pathlib import Path

import tyro


class StructureChecker:
    def __init__(
        self,
        root_path: Path,
        target_num: int = 1000,
        check_score: bool = True,
    ):
        self.root_path = Path(root_path)
        self.check_score = check_score
        self.target_num = target_num
        self.errors = []
        self.warnings = []

    def check_structure(self):
        """Main validation function."""
        print(f"Checking structure at: {self.root_path}")
        print("=" * 80)

        if not self.root_path.exists():
            self.errors.append(f"Root path does not exist: {self.root_path}")
            return False

        if not self.root_path.is_dir():
            self.errors.append(f"Root path is not a directory: {self.root_path}")
            return False

        # Get all subdirectories in root
        folders = [f for f in self.root_path.iterdir() if f.is_dir()]

        if not folders:
            self.errors.append("No folders found in root directory")
            return False

        print(f"Found {len(folders)} folders in root\n")

        # Check each folder
        for folder in sorted(folders):
            self.check_folder(folder)

        return len(self.errors) == 0

    def check_folder(self, folder_path: Path) -> bool:
        """Check a single folder for correct structure."""
        print(f"\nChecking: {folder_path.name}")
        print("-" * 80)

        # Get all subdirectories
        subdirs = [d for d in folder_path.iterdir() if d.is_dir()]
        subdir_names = {d.name for d in subdirs}

        # Check for diversity folder
        if "diversity" not in subdir_names:
            self.errors.append(f"{folder_path.name}: Missing 'diversity' folder")
            print("  ✗ Missing 'diversity' folder")
        else:
            print("  ✓ 'diversity' folder found")
            self.check_diversity_folder(folder_path / "diversity", folder_path.name)

        # Check for numbered folders
        expected_nums = {"42", "1234", "21344", "304516", "405671", "693042"}
        found_nums = subdir_names & expected_nums

        if len(found_nums) != 6:
            missing = expected_nums - found_nums
            self.errors.append(
                f"{folder_path.name}: Expected 6 numbered folders {sorted(expected_nums)}, "
                f"found {len(found_nums)}. Missing: {sorted(missing)}"
            )
            print(f"  ✗ Found {len(found_nums)}/6 numbered folders. Missing: {sorted(missing)}")
        else:
            print("  ✓ All 6 numbered folders found")

        # Check each numbered folder
        for num in sorted(found_nums):
            self.check_num_folder(folder_path / num, folder_path.name, num)

        # Check for unexpected folders
        unexpected = subdir_names - expected_nums - {"diversity"}
        if unexpected:
            self.warnings.append(f"{folder_path.name}: Unexpected folders found: {sorted(unexpected)}")
            print(f"  ⚠ Unexpected folders: {sorted(unexpected)}")

    def check_num_folder(self, num_folder_path: Path, parent_name: str, num: str) -> bool:
        """Check a numbered folder for correct files."""
        prefix = f"  [{num}]"

        if not num_folder_path.exists():
            self.errors.append(f"{parent_name}/{num}: Folder does not exist")
            print(f"{prefix} ✗ Folder does not exist")
            return

        # Count files by pattern
        files = list(num_folder_path.iterdir())

        gen_files = [f for f in files if f.name.startswith("gen") and f.suffix == ".png"]
        prompt_files = [f for f in files if f.name.startswith("prompt") and f.suffix == ".txt"]

        # Check counts
        errors_in_folder = []

        if len(gen_files) != self.target_num:
            errors_in_folder.append(f"gen*.png: {len(gen_files)}/{self.target_num}")

        if len(prompt_files) != self.target_num:
            errors_in_folder.append(f"prompt*.txt: {len(prompt_files)}/{self.target_num}")

        # Only check scores if flag is enabled
        if self.check_score:
            score_files = [f for f in files if f.name.startswith("score") and f.suffix == ".json"]
            avg_score_file = num_folder_path / "average_score.json"

            if len(score_files) != self.target_num:
                errors_in_folder.append(f"score*.json: {len(score_files)}/{self.target_num}")

            if not avg_score_file.exists():
                errors_in_folder.append("average_score.json: missing")

        if errors_in_folder:
            error_msg = f"{parent_name}/{num}: " + ", ".join(errors_in_folder)
            self.errors.append(error_msg)
            print(f"{prefix} ✗ Errors found:")
            for err in errors_in_folder:
                print(f"{prefix}     - {err}")
        else:
            if self.check_score:
                print(
                    f"{prefix} ✓ All files present ({self.target_num} gen, {self.target_num} prompt, {self.target_num} score, 1 average_score)"
                )
            else:
                print(f"{prefix} ✓ All files present ({self.target_num} gen, {self.target_num} prompt)")

    def check_diversity_folder(self, diversity_path: Path, parent_name: str) -> bool:
        """Check the diversity folder for correct files."""
        prefix = "  [diversity]"

        if not diversity_path.exists():
            self.errors.append(f"{parent_name}/diversity: Folder does not exist")
            print(f"{prefix} ✗ Folder does not exist")
            return

        # Count files
        files = list(diversity_path.iterdir())

        diversity_files = [f for f in files if f.name.startswith("diversity") and f.suffix == ".json"]
        avg_diversity_file = diversity_path / "average_diversity.json"

        # Check counts
        errors_in_folder = []

        if len(diversity_files) != self.target_num:
            # Subtract 1 if average_diversity.json is included in the count
            actual_count = len(diversity_files)
            if avg_diversity_file in diversity_files:
                actual_count -= 1

            if actual_count != self.target_num:
                errors_in_folder.append(f"diversity*.json: {actual_count}/{self.target_num}")

        if not avg_diversity_file.exists():
            errors_in_folder.append("average_diversity.json: missing")

        if errors_in_folder:
            error_msg = f"{parent_name}/diversity: " + ", ".join(errors_in_folder)
            self.errors.append(error_msg)
            print(f"{prefix} ✗ Errors found:")
            for err in errors_in_folder:
                print(f"{prefix}     - {err}")
        else:
            print(f"{prefix} ✓ All files present ({self.target_num} diversity, 1 average_diversity)")

    def print_summary(self) -> int:
        """Print summary of validation results."""
        print("\n" + "=" * 80)
        print("SUMMARY")
        print("=" * 80)

        if self.warnings:
            print(f"\n⚠ Warnings ({len(self.warnings)}):")
            for warning in self.warnings:
                print(f"  - {warning}")

        if self.errors:
            print(f"\n✗ Errors ({len(self.errors)}):")
            for error in self.errors:
                print(f"  - {error}")
        else:
            print("\n✓ No errors found! Structure is valid.")

        print("\n" + "=" * 80)

        return len(self.errors) == 0


def main(root_path: Path, target_num: int = 1000, check_score: bool = True):
    root_path = root_path.expanduser().resolve()
    if not root_path.is_dir():
        raise ValueError(f"Not a directory: {root_path}")

    checker = StructureChecker(root_path, target_num, check_score)
    checker.check_structure()
    return checker.print_summary()


if __name__ == "__main__":
    tyro.cli(main)
